spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productivity_suite_db_test?useSSL=false&serverTimezone=UTC
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver