spring:
  application:
    name: productivity-suite
#  profiles:
#    active: dev
  datasource:
    url: jdbc:postgresql://dpg-d124sns9c44c73fus9d0-a.oregon-postgres.render.com/productivity_suite_db_trs3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: XpcrExo8ZE9tz4Y6v6yC6SUGankGROQM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  paths-to-match: /productivity-suite/api/v1/**
  api-docs:
    path: /v3/api-docs
application:
  frontend-urls: http://localhost:3000, https://productivity-suite-app.netlify.app
  central-bank-url: https://forex.cbm.gov.mm