name: CI workflow
on:
  workflow_dispatch:  #Manually run the pipeline
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - 'dev-*'
jobs:
  # jobs id
  build:
    runs-on: ubuntu-latest
    # output the cache hit or miss
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java on the runner OS
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{github.sha}}-gradle-cache-key

      - name: Build the app
        run: ./gradlew clean build --no-daemon


