name: CI workflow
on:
  workflow_dispatch: #Manually run the pipeline
  pull_request:
      branches:
        - main
        - develop
  push:
      branches:
        - develop
        - 'dev-*'
jobs:
  application_build:
    name: "Build the Application"
    uses: ./.github/workflows/build.yaml







